shell zsh
allow_remote_control yes

background_opacity 0.75
background_blur 1

font_family      JetBrains Mono
font_size        12.0

cursor_blink_interval 0

background #1a1111
foreground #f0dede

# 16-color palette from matugen
color0  #524343
color1  #ffb4ab
color2  #e5c18d
color3  #e6bdbc
color4  #ffb3b3
color5  #ffdad9
color6  #ffddae
color7  #f0dede
color8  #a08c8c
color9  #ffb4ab
color10 #e5c18d
color11 #e6bdbc
color12 #ffb3b3
color13 #ffdad9
color14 #ffddae
color15 #ffffff

window_padding_width 12
