shell zsh

background_opacity 0.75
background_blur 1

font_family      JetBrains Mono
font_size        12.0

cursor_blink_interval 0

background #1a1111
foreground #f0dedd

# 16-color palette from matugen
color0  #534342
color1  #ffb4ab
color2  #e3c28c
color3  #e7bdba
color4  #ffb3af
color5  #ffdad8
color6  #ffdea9
color7  #f0dedd
color8  #a08c8b
color9  #ffb4ab
color10 #e3c28c
color11 #e7bdba
color12 #ffb3af
color13 #ffdad8
color14 #ffdea9
color15 #ffffff

window_padding_width 12
