shell zsh

background_opacity 0.75
background_blur 1

font_family      JetBrains Mono
font_size        12.0

cursor_blink_interval 0

background #191113
foreground #efdfe1

# 16-color palette from matugen
color0  #514346
color1  #ffb4ab
color2  #edbd92
color3  #e3bdc4
color4  #ffb1c4
color5  #ffd9e0
color6  #ffdcbf
color7  #efdfe1
color8  #9e8c8f
color9  #ffb4ab
color10 #edbd92
color11 #e3bdc4
color12 #ffb1c4
color13 #ffd9e0
color14 #ffdcbf
color15 #ffffff

window_padding_width 12
