monitor.alsa.rules = [
  {
    matches = [{ device.name = "alsa_card.pci-0000_0c_00.6" }]
    actions = {
      update-props = {
        device.profile = "output:analog-stereo+input:analog-stereo"
      }
    }
  }
  {
    matches = [{ device.name = "alsa_card.usb-Maono_DGM20_USB_Microphone_20230101-00" }]
    actions = {
      update-props = {
        device.profile = "input:analog-stereo"
      }
    }
  }
]
